### ISSUE TITLE
Supabase support?

### ISSUE THREAD

**Issue by nicopace** [alyssaxuu/mapus#3]
Hi!
Thanks for a great project!
It looks like it depends on firebase, but it doesn't need to.
There is a replacement for firebase called supabase... Not sure how hard could be to migrate, but it is definitely worth trying as it would mean no external dependencies.
https://supabase.io/

**Comment by alyssaxuu** [comment]
It's a great tool for sure, but if I were to use it it would be more expensive than Firebase even (based on the numbers in the pricing, they also have more limits in their free plan). And if I self-hosted Supabase then it would overcomplicate things, I used Firebase so people can quickly get started with Mapus. They'd have to essentially set up a backend for it.

**Comment by nicopace** [comment]
Thanks for your super quick response!
I understand your arguments, thanks for putting time to write them down.
We might want to explore extending your design for community networks scenario design for the librerouter.org ...
It will not happen now (as we have our hands full for two lifetimes), but if we do so, this might end up being our way of giving back.

Thanks!
